name=Mosquetteer
version=0.0.1
author=D. Xavier
maintainer=D. Xavier <davix@noreply.com>
sentence=A lightweight MQTT and Home Assistant integration wrapper for ESP32 devices.
paragraph=A lightweight MQTT and Home Assistant integration wrapper for ESP32 devices.
category=Communication
url=https://github.com/davirxavier/Mosquetteer
architectures=esp32
license=MIT
includes=Mosquetteer.h
